name: admin_web
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  cloud_functions: ^4.6.5
  firebase_storage: ^11.6.5
  fl_chart: ^0.66.2
  provider: ^6.1.2
  pdf: ^3.11.0
  printing: ^5.13.1
  http: ^1.2.2
  syncfusion_flutter_datepicker: ^28.1.38
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/bgg.jpg
    - assets/report_template_bg.jpg
